#!/usr/bin/env bash

read_input() {
  while IFS= read -r line; do
    IFS='=' read -r key value <<< "${line}"
    case "${key}" in
      protocol) protocol=${value};;
      host)     host=${value};;
      username) username=${value};;
      password) password=${value};;
    esac
  done
}

case "${1}" in
  get)
    read_input
    pass git/${protocol}/${host}
    ;;
  store)
    read_input
    printf "username=${username}\npassword=${password}\n" | pass insert -m git/${protocol}/${host}
    ;;
  *)
    echo "unknown verb: ${1}"
    exit 1
esac
