#!/bin/bash

branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch" == "HEAD" ]; then
  echo "only works on named branches"
  exit 1
fi

remote=$(git config branch.${branch}.remote)
upstream=$(git config branch.${branch}.merge)

if [ "${1}" != "" ]; then
  target=${1}
else
  target=$(git rev-parse --abbrev-ref ${branch}@{upstream})
fi

git log ..${target}
