#!/bin/bash

CURRENT_BRANCH=$(git name-rev --name-only --refs="refs/heads/*" `git symbolic-ref -q HEAD`)

if [ -n "${CURRENT_BRANCH}" ]; then
  
  TARGET="${1}"
  
  if [ -z "${TARGET}" ]; then
    TRACKING_REPOSITORY="$(git config branch.${CURRENT_BRANCH}.remote)"
    
    # there is a tracking repository
    if [ "${TRACKING_REPOSITORY}" != "" ]; then
      REMOTE_REPOSITORY="${TRACKING_REPOSITORY}"
      REMOTE_BRANCH="$(git config branch.${CURRENT_BRANCH}.merge | sed -e 's#^[^/]*/[^/]*/##')"
      TARGET="${REMOTE_REPOSITORY}/${REMOTE_BRANCH}"
    fi
  fi
  
  echo "To: ${TARGET}"
  echo ""
  
  git log ${TARGET}..
fi
