#!/usr/bin/env bash

store=${PASSWORD_STORE_DIR:-${HOME}/.password-store}

if [ ! -d "${store}" ]; then
  echo "pass store does not exist"
  exit 1
fi

read_input() {
  while IFS= read -r line; do
    IFS='=' read -r key value <<< "${line}"
    case "${key}" in
      protocol) protocol=${value};;
      host)     host=${value};;
      username) username=${value};;
      password) password=${value};;
    esac
  done

  if [ -z "${protocol}" ] || [ -z "${host}" ]; then
    echo "protocol and host must both be set"
    exit 1
  fi

  passfile="git/${protocol}/${host}"
}

case "${1}" in
  get)
    read_input
    pass show ${passfile}
    ;;
  store)
    read_input
    if [ ! -f "${store}/${passfile}.gpg" ]; then
      printf "username=${username}\npassword=${password}\n" | pass insert -m git/${protocol}/${host}
    fi
    ;;
  *)
    echo "unknown verb: ${1}"
    exit 1
esac
