#!/bin/bash

dir="$(dirname "$(readlink -m "$0")")"
. "$dir/bash-functions"

usage() {
	blue "Usage:"
	cat <<-USAGE
		  $0
		  $0 repo
		  $0 repo/branch
		Example:
		  $0
		  $0 origin
		  $0 origin/master
		USAGE
	exit 1
}

fetch=1

while [[ "$1" == -* ]]; do
	case "$1" in
		--no-fetch)
			fetch=0
			;;
		*)
			usage
			;;
	esac
	shift
done

parse_source_args "$@"

clear

green Local status
git --no-pager status
(( "$?" != 0 )) && exit $?

green Stashes
git --no-pager stash list --oneline

if (( "$fetch" == 1 )); then
	green "Fetching $source..."
	git --no-pager fetch "$source" -v
fi

green "Incoming changes:"
"$dir/git-incoming" --no-pager "$branch"

green "Outgoing changes:"
"$dir/git-outgoing" --no-pager "$branch"

echo
