#!/bin/sh

set -e

die() { echo $*; exit 1; }

[ -z "$(git status --porcelain)" ] || die "must have clean git working tree"

git branch --merged master --format "%(refname:short)" | grep -v "^master$" | while read branch; do
  git branch -D $branch
done
