#!/usr/bin/env bash

read_input() {
  while IFS= read -r line; do
    IFS='=' read -r key value <<< "${line}"
    case "${key}" in
      protocol) protocol=${value};;
      host)     host=${value};;
      username) username=${value};;
      password) password=${value};;
    esac
  done
}

case "${1}" in
  get)
    read_input
    pass git/${protocol}/${host}
    ;;
  store)
    read_input
    credentials=$(printf "username=${username}\npassword=${password}\n")
    echo ${credentials} >  /tmp/c.txt
    pass git/${protocol}/${host} > /tmp/d.txt
    if [ "${credentials}" != "$(pass git/${protocol}/${host})" ]; then
      echo "${credentials}"| pass insert -m git/${protocol}/${host}
    fi
    ;;
  *)
    echo "unknown verb: ${1}"
    exit 1
esac
