#!/bin/bash

green() {
	echo
	echo -e "\033[1;32m$*\033[0m"
}

usage() {
	cat <<-USAGE
		Usage:
		  $0
		  $0 repo
		  $0 repo/branch
		Example:
		  $0
		  $0 origin
		  $0 origin/master
		USAGE
	exit 1
}

fetch=1

while [[ "$1" == -* ]]; do
	case "$1" in
		--no-fetch)
			fetch=0
			;;
		*)
			usage
			;;
	esac
	shift
done

case "$#" in
	1)
		remote_branch="$1"
		if [[ "$remote_branch" == */* ]]; then
			remote_source="$(echo "$1" | sed -e 's#^remote/##g' -e 's#/.*##g')"
		else
			remote_source="$remote_branch"
			remote_branch="$remote_branch/master"
		fi
		;;
	0)
		git_remote_source="$(dirname "$(readlink "$0")")/git-remote-source"
		remote_branch="$("$git_remote_source")"
		remote_source="$(echo "$remote_branch" | sed -e 's#/.*##')"
		;;
	*)
		usage
		;;
esac

clear

green Local status
git --no-pager status
(( "$?" != 0 )) && exit $?

green Stashes
git --no-pager stash list --oneline

if (( "$fetch" == 1 )); then
	green "Fetching $remote_source..."
	git --no-pager fetch "$remote_source" -v
fi

green "Incoming changes:"
git --no-pager incoming "$remote_branch"

green "Outgoing changes:"
git --no-pager outgoing "$remote_branch"

echo
