#!/bin/sh

set -e

die() { echo $*; exit 1; }

[ -z "$(git status --porcelain)" ] || die "must have clean git working tree"

git checkout master

git for-each-ref --format='%(refname:strip=2)' refs/heads/ | while read branch; do
  echo "branch: $branch"
  case $branch in
    master)
      ;;
    *)
      if [ -z "$(git log ..$branch)" ]; then
        git branch -D $branch
      else
        git checkout $branch
        git rebase master
        git push origin $branch -f
      fi
      ;;
  esac
done
