#!/bin/sh

CURRENT_BRANCH=$(git branch &>/dev/null; if [ $? -eq 0 ]; then echo "$(git branch | grep '^*' |sed s/\*\ //)"; fi)
CURRENT_DIR=$(basename $(pwd))

PATCH_DIR="${HOME}/Documents/Patches/${CURRENT_DIR}"

TARGET_BRANCH="${1-master}"
DEST="${PATCH_DIR}/${CURRENT_BRANCH}-${TARGET_BRANCH}.diff"
mkdir -p "$(dirname $DEST)"

git format-patch ${TARGET_BRANCH} --stdout > $DEST

