#!/bin/bash

usage() {
	cat <<-USAGE
		Usage:
		  $0
		    Pulls and pushes.
		  $0 --stash
		    Saves the current status in stash, then does a normal sync.
	USAGE
	exit 1
}

red() {
	echo
	echo -e "\033[1;31m$*\033[0m"
}

green() {
	echo
	echo -e "\033[1;32m$*\033[0m"
}

stat() {
	status="$(git status --porcelain 2> /dev/null)"
	if (( $? != 0 )) || [[ "$status" != "" ]]; then
		red Stopping
		if [[ "$1" != "" ]]; then
			echo "$1"
		fi
		echo
		git status
		echo
		exit 1
	fi
}

stash=0
while [[ "$1" == -* ]]; do
	case "$1" in
		--stash)
			stash=1
			;;
		*)
			usage
			;;
	esac
	shift
done
if (( "$#" != 0 )); then
	usage
fi

if (( $stash == 1 )); then
	old_stash_count=$(git stash list | wc -l)

	green Stashing
	git stash save

	new_stash_count=$(git stash list | wc -l)
	if (( $new_stash_count == $old_stash_count )); then
		# The stash save didn't do anything; turn off stashing so we don't pop anything either.
		stash=0
	fi
else
	stat "To stash before and after syncing, call git sync --stash"
fi

green Pulling
git pull "$@"
stat

green Pushing
git push "$@"
stat

if (( $stash == 1 )); then
	green Popping the stash
	git stash pop
fi

echo
