#!/bin/bash

if [ -z "${1}" ]; then
  echo "git-switch <branch>"
  exit;
fi

NEW_BRANCH=${1}
CURRENT_BRANCH=$(git branch &>/dev/null; if [ $? -eq 0 ]; then echo "$(git branch | grep '^*' |sed s/\*\ //)"; fi)

git stash save autostash &>/dev/null
git checkout ${NEW_BRANCH}

if [ "$?" -eq "1" ]; then
  git branch ${NEW_BRANCH}
  git checkout ${NEW_BRANCH}
fi

AUTOSTASH=$(git stash list | grep "${NEW_BRANCH}: autostash" | tail -n 1 | cut -d":" -f1)

if [ -n "${AUTOSTASH}" ]; then
  git stash apply ${AUTOSTASH} && git stash drop ${AUTOSTASH}
fi
