#!/bin/sh

CURRENT_BRANCH=$(git name-rev HEAD | cut -d " " -f2)

if [ "${CURRENT_BRANCH}" != "" ]; then
  
  TARGET="${1}"
  
  if [ -z "${TARGET}" ]; then
    TRACKING_REPOSITORY="$(git config branch.${CURRENT_BRANCH}.remote)"
    
    # there is a tracking repository
    if [ "${TRACKING_REPOSITORY}" != "" ]; then
      REMOTE_REPOSITORY="${TRACKING_REPOSITORY}"
      REMOTE_BRANCH="$(git config branch.${CURRENT_BRANCH}.merge | sed -e 's#^[^/]*/[^/]*/##')"
      TARGET="${REMOTE_REPOSITORY}/${REMOTE_BRANCH}"
    fi
  fi
  
  echo "From: ${TARGET}"
  echo ""
  
  git log ..${TARGET}
fi
