#!/bin/sh

CURRENT_BRANCH=$(git name-rev --name-only --refs="refs/heads/*" `git symbolic-ref -q HEAD`)
CURRENT_DIR=$(basename $(pwd))

PATCH_DIR="${HOME}/Documents/Patches/${CURRENT_DIR}"

mkdir -p ${PATCH_DIR}

git format-patch master --stdout > ${PATCH_DIR}/${CURRENT_BRANCH}.diff

