#!/bin/sh

if [ -z "${1}" ]; then
  echo "git-switch <branch>"
fi


NEW_BRANCH=${1}
CURRENT_BRANCH=$(git name-rev HEAD | cut -d " " -f2)

git stash save autostash &>/dev/null
git checkout ${NEW_BRANCH}

if [ "$?" == "1" ]; then
  git branch ${NEW_BRANCH}
  git checkout ${NEW_BRANCH}
fi

AUTOSTASH=$(git stash list | grep "${NEW_BRANCH}: autostash" | tail -n 1 | cut -d":" -f1)

if [ "${AUTOSTASH}" != "" ]; then
  git stash apply ${AUTOSTASH} && git stash drop ${AUTOSTASH}
fi
